DROP TABLE IF EXISTS users, portfolio, stocks;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS stocks (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(255),
  user_id VARCHAR(255) NOT NULL REFERENCES users(username)
);